### PR TITLE
add ClusterServiceVersion resource for post-deletion

### PR DESCRIPTION
**Pull request by mabulgu**
Fix regarding to the issue: #19

### CODE REVIEW

**Comment by mabulgu** [comment]
I suppose there is sth wrong with the chart listing. Or am I doing sth wrong?  (using helm 3.1.2)

**Comment by mabulgu** [comment]
I think its because of the chart version which i did not increment. Will wait for the suggestions and fix the build after that..

**Comment by ckavili** [comment]
Oh sorry, this one is here for quite some time :) 
I tried to install an operator with this chart but couldn’t see any helm annotation on CSV , then when I tried to uninstall the chart, CSV got deleted but I also got the following error:
```
$helm uninstall operatorhub-0-1588605471
Error: uninstallation completed with 1 error(s): unable to build kubernetes object for post-delete hook operatorhub/templates/clusterserviceversion.yaml: error validating "": error validating data: ValidationError(ClusterServiceVersion): missing required field "spec" in com.coreos.operators.v1alpha1.ClusterServiceVersion
```
(Apart from the error I got 😅) for helm installation, we can have CSV as a template. Before I just would like to hear other ideas since CSV is created automatically with subs so this feels a bit hack :D (note that one can't do ` helm template .. | oc apply -f-` due to missing spec info on the template.) 

I also came across these; regarding https://github.com/argoproj/argo-cd/issues/2999 I guess now when an Operator is deployed through ArgoCD 1.6.0, the CSV can be deleted when the application definition is deleted since there is this hardcoded link. And it seems there won’t be any ref between the subscription and the csv. (https://github.com/operator-framework/operator-lifecycle-manager/issues/1283)

**Comment by mabulgu** [comment]
Hi @ckavili,

Thanks for checking out!

For the error you got: _which operator_ did you install and uninstall? Since it's been a while I need to check it again with the one you did try in case any updates etc. with the master branch..

I think keeping a CSV is not a good idea TBH, because IMHO the behavior should be left as-is: in this case if it is the operatorhub itself to create the CSV, it should be left like that because it is its duty in the normal flow.

**Comment by eformat** [comment]
Hi @mabulgu i'm going to close this one i think? please re-open if you think this is still an issue. Cheers 🦓🦓

**Comment by mabulgu** [comment]
This issue still exists. Regarding the last Labs residency, I faced this problem when we use the operator chart.

After deletion, it should also delete the relevant CSV which OCP UI also complains. Please see the relevant screenshots and screencasts here #19 

Can we reopen this pls?

**Pull request closed without merging**
